---
title: "Portfólio WEB de Iniciação Científica"
format: html
---

# Introdução
A exploração do ambiente espacial, mais especificamente as órbitas terrestres, tem sido de suma importância e um dos maiores triúnfos da engenharia e física da atualidade. Desde os primeiros lançamentos de satélites, a previsão das trajetórias de objetos em órbita com alta precisão se tornou indispensável para a comunicação, GPS, pesquisas científicas e outros. Nesse contexto, a Estação Espacial Internacional(International Space Station, ISS), literalmete um laboratório em constante queda livre, se torna objeto ideal de estudo para a demonstração das leis da mecânica clássica e o poder de previsão.

Este Portfólio WEB apresenta uma proposta didática para o ensino das técnicas de simulção orbital utilizando a linguagem de programação Python, tomando como estudo de caso a trajetória da ISS em torno da Terra. O objetivo central é demonstrar como modelos matemáticos podem ser traduzidos em algoritimos, com capacidade de prever o comportamento de satélites em órbitas de baixa altitude (Low Earth Orbits, LEOs). Através de uma abordagem prática, exploramos como as forças gravitacionais e outras variáveis moldam o movimentos dos objetos e como métodos de integração numérica, como Método de Euler e Runge Kutta, permitem estimar com alta precisão a posição e a velocidade da estação ao longo do tempo.

A intenção desse trabalho é ser mais que apenas um repositório de códigos, é dar contextualização sobre a física por de trás dos algoritimos. Ao longo das seções serão discutidos temas como : Elementos Orbitais; Equações Diferenciais Ordinárias (EDOs); utilização de scripts em Python e bibliotecas como Numpy e Matplot.lib, para visualização 3D das órbitas; achatamento terrestre e coeficiente $J2$; Arrasto Atmosférico e etc.

Dessa forma esse portfólio serve como uma ponte entre a física teórica e a experimentação computacional, ofertando um recurso interativo aos entusiastas que queiram aprofundar seus conhecimentos sobre dinâmica orbital.

# 1. Órbitas Keplerianas 

O ponto de partida para entender a dinâmica orbital é o problema de dois corpos. Esse sistema consiste em um corpo esférico central (Terra) de massa = $M$ e um satélite (ISS) de massa = $m$, onde temos a condição $M >> m$. Com a atração gravitacional ($F_g$) sendo a única força atuante no sistema, dada pela equação:

$$
F_g = - G \frac{M \cdot m}{r^2} \hat{r} 
$$ {#eq-Força-G}

onde, $r$ $\cdot$ $\hat{r}$ = $\textbf{r}$ é o vetor posição do satélite com origem no centro da Terra. Assim, temos a seguinte equação quando aplicamos a força na 2ª Lei de Newton: 

$$  
\ddot r + \frac{\mu}{r^3} \textbf{r} = 0 
$$ {#eq-2ª-Lei}





